name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: 'Backend Changes'
    labels:
      - 'backend'
  - title: 'Frontend Changes'
    labels:
      - 'frontend'
  - title: 'Security System Changes'
    labels:
      - 'security'
  - title: 'Control System Changes'
    labels:
      - 'control'

template: |
  ## Changes in the project (from develop branches):

  $CHANGES

  ## Contributors
  Thanks to the following contributors:
  $CONTRIBUTORS
