name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'  # Uruchamia workflow, gdy wypychany jest tag pasujący do wzorca "v*"
  workflow_dispatch:  # Pozwala na ręczne uruchomienie workflow

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Checkout develop branch for submodules
        run: |
          # Przełącz na branch 'develop' w głównym repozytorium
          git checkout develop
          
          # Przełącz każdy submoduł na branch 'develop'
          cd webapp/backend && git checkout develop || true && cd -
          cd webapp/frontend && git checkout develop || true && cd -
          cd embedded/security && git checkout develop || true && cd -
          cd embedded/control && git checkout develop || true && cd -

      - name: Gather changes from develop branches
        run: |
          echo "## Changes in the project (from develop branches)" > changes.md
          
          echo "### Backend Changes" >> changes.md
          git log --pretty=format:"- %h %s (%an)" origin/develop -- webapp/backend || true >> changes.md
          
          echo "### Frontend Changes" >> changes.md
          git log --pretty=format:"- %h %s (%an)" origin/develop -- webapp/frontend || true >> changes.md
          
          echo "### Security System Changes" >> changes.md
          git log --pretty=format:"- %h %s (%an)" origin/develop -- embedded/security || true >> changes.md
          
          echo "### Control System Changes" >> changes.md
          git log --pretty=format:"- %h %s (%an)" origin/develop -- embedded/control || true >> changes.md

      - name: Create Release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: ${{ github.ref_name }}  
          release_name: ${{ github.ref_name }}  
          body_path: changes.md 
          draft: false
          prerelease: false
